apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qwwyenc2e-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:10461dd990eb33887134fa9c19ab74c196c1fab9@sha256:23c9a9e6bb3aa3f120f1ac05aa0b0225d971d087a262de07ae088c0b1af943ed
          name: container-image
